### ISSUE TITLE
Flaky test: OSS e2e: can delete a token

### ISSUE THREAD

**Issue by TCL735** [influxdata/ui#3036]
Clockface 3 changes required updating the tests in `cypress/e2e/shared/tokens.test.ts` including the "can delete a token" test.

There has been repeated failures for the OSS e2e runs of "can delete a token".

The logged output is:
```
CypressError: Timed out retrying after 10050ms: `cy.click()` failed because this element is detached from the DOM.

`<button class="cf-button cf-button-xs cf-button-colorless cf-button-square" tabindex="0" type="button" data-testid="context-delete-menu--button">...</button>`

Cypress requires elements be attached in the DOM to interact with them.

The previous command that ran was:

  > `cy.get()`

This DOM element likely became detached somewhere between the previous and current command.

Common situations why this happens:
  - Your JS framework re-rendered asynchronously
  - Your app code reacted to an event firing and removed the element

You typically need to re-query for the element or add 'guards' which delay Cypress from running new commands.

https://on.cypress.io/element-has-detached-from-dom
    at $Cy.ensureAttached (https://ingress/__cypress/runner/cypress_runner.js:142429:24)
    at runAllChecks (https://ingress/__cypress/runner/cypress_runner.js:131064:12)
    at retryActionability (https://ingress/__cypress/runner/cypress_runner.js:131141:16)
    at tryCatcher (https://ingress/__cypress/runner/cypress_runner.js:10798:23)
    at Function.Promise.attempt.Promise.try (https://ingress/__cypress/runner/cypress_runner.js:8072:29)
    at tryFn (https://ingress/__cypress/runner/cypress_runner.js:147090:21)
    at whenStable (https://ingress/__cypress/runner/cypress_runner.js:147128:12)
    at https://ingress/__cypress/runner/cypress_runner.js:146620:16
    at tryCatcher (https://ingress/__cypress/runner/cypress_runner.js:10798:23)
    at Promise._settlePromiseFromHandler (https://ingress/__cypress/runner/cypress_runner.js:8733:31)
    at Promise._settlePromise (https://ingress/__cypress/runner/cypress_runner.js:8790:18)
    at Promise._settlePromise0 (https://ingress/__cypress/runner/cypress_runner.js:8835:10)
    at Promise._settlePromises (https://ingress/__cypress/runner/cypress_runner.js:8915:18)
    at Promise._fulfill (https://ingress/__cypress/runner/cypress_runner.js:8859:18)
    at https://ingress/__cypress/runner/cypress_runner.js:10473:46
From Your Spec Code:
    at Context.eval (https://ingress/__cypress/tests?p=cypress/e2e/shared/tokens.test.ts:318:59)
```

**Comment by ChitlangeSahas** [comment]
closed in #3084
