### ISSUE TITLE
An InfluxDB error has occurred

### ISSUE THREAD

**Issue by philippelenaour** [influxdata/ui#3989]
Hi,

i’m using InfluxDB Cloud.

I have this problem on a specific dashboard “Linux System” from the community repository, most of the graphs display this message and can’t edit anything.

I tried to remove the bucket and recreate it, push the data to another bucket. Remove the template, remoce all templates … etc …

Everything was working yesterday.

In the developper console I have this message:
react_devtools_backend.js:4061 TypeError: Cannot read properties of null (reading ‘map’)
at 26.40a23e1274.js:1:553699
at Array.forEach ()
at l (26.40a23e1274.js:1:553645)
at i (26.40a23e1274.js:1:552900)
at P (26.40a23e1274.js:1:342356)
at sa (react-dom.production.min.js:157:137)
at Zs (react-dom.production.min.js:267:460)
at Tu (react-dom.production.min.js:250:347)
at Du (react-dom.production.min.js:250:278)
at Su (react-dom.production.min.js:250:138)

What can I do ?

I also have an error in the usage screen. Not the same JS error:

TypeError: Cannot set properties of undefined (setting ‘opacity’)
at /static/25.bb7eab8a5f.js:2:1340772
at ks (/static/25.bb7eab8a5f.js:2:1344748)
at Es (/static/25.bb7eab8a5f.js:2:1344870)
at /static/26.40a23e1274.js:1:553747
at Array.forEach ()
at l (/static/26.40a23e1274.js:1:553645)
at i (/static/26.40a23e1274.js:1:552900)
at P (/static/26.40a23e1274.js:1:342356)
at sa (/static/25.bb7eab8a5f.js:2:2568016)
at Zs (/static/25.bb7eab8a5f.js:2:2620097)
cs @ react-dom.production.min.js:216

**Comment by kristinarobinson** [comment]
Thanks for writing up the issue.  I'll have my team take a lot to see if there are operational issues on our side.

**Comment by backbone-link** [comment]
I am also seeing this

**Comment by kristinarobinson** [comment]
We found the root cause of the issue, and have a fix ready.  It should make its way to production shortly.

**Comment by backbone-link** [comment]
Awesome thank you guys
