### ISSUE TITLE
InfluxDB 2.7.0: Dashboard Crash - An InfluxDB error has occurred. Please report the issue here.

### ISSUE THREAD

**Issue by KellyM001** [influxdata/ui#6760]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior:
1. Create a dashboard
2. In the Dashboards page select 'Sort by Modified (oldest)' (or newest)
3. Navigate away from the Dashboards page to another page (eg Notebooks)
4. Navigate back to the Dashboards page
5. The error occurs

Note this problem occurs only if you select 'Sort by Modified`. If you select 'Sort by Name' no problem occurs.

**Expected behavior:**
Navigating back to the Dashboards page should not result in an error

**Actual behavior:**
Empty page with text:
> An InfluxDB error has occurred. Please report the issue 
> [here](https://github.com/influxdata/ui/issues/new?template=bug_report.md)
> .

**Visual Proof:**
![image](https://github.com/influxdata/ui/assets/78883429/79634aad-3a80-4a68-b681-412f5ce49c2d)

## About your environment
**Environment info:**
Linux 5.4.0-152-generic x86_64
InfluxDB v2.7.0 (git: 85f725f8b9) build_date: 2023-04-05T15:32:25Z
InfluxDB running in a docker container
InfluxDB UI accessed via Microsoft Edge Version 114.0.1823.67 (Official build) (64-bit)

**Config:**
Default config

**Comment by zoesteinkamp** [comment]
I might need some more details, was there any errors in the console? I assume refreshing the page might have fixed the issue?

**Comment by activeliang** [comment]
same error

**Comment by KellyM001** [comment]
> I might need some more details, was there any errors in the console? I assume refreshing the page might have fixed the issue?

@zoesteinkamp Sorry for the late response. Yes there are errors in the console (see below), and refreshing the dashboard page reloaded it fine (dashboards ordered A-Z by default). I've updated to v2.7.5 and the problem still exists.

Console errors:
```
react-dom.production.min.js:216 
 TypeError: Cannot destructure property 'label' of 'd.find(...)' as it is undefined.
    at c (ResourceSortDropdown.tsx:38:10)
    at ca (react-dom.production.min.js:157:137)
    at Qa (react-dom.production.min.js:180:154)
    at Vc (react-dom.production.min.js:269:343)
    at Ts (react-dom.production.min.js:250:347)
    at Es (react-dom.production.min.js:250:278)
    at Ss (react-dom.production.min.js:250:138)
    at vs (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)

errors.ts:63 
 TypeError: Cannot destructure property 'label' of 'd.find(...)' as it is undefined.
    at c (ResourceSortDropdown.tsx:38:10)
    at ca (react-dom.production.min.js:157:137)
    at Qa (react-dom.production.min.js:180:154)
    at Vc (react-dom.production.min.js:269:343)
    at Ts (react-dom.production.min.js:250:347)
    at Es (react-dom.production.min.js:250:278)
    at Ss (react-dom.production.min.js:250:138)
    at vs (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)

queryStringConfig.ts:7 
 TypeError: Cannot destructure property 'label' of 'd.find(...)' as it is undefined.
    at c (ResourceSortDropdown.tsx:38:10)
    at ca (react-dom.production.min.js:157:137)
    at Vc (react-dom.production.min.js:267:460)
    at Ts (react-dom.production.min.js:250:347)
    at Es (react-dom.production.min.js:250:278)
    at Ss (react-dom.production.min.js:250:138)
    at vs (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Go (react-dom.production.min.js:122:325)

queryStringConfig.ts:7 
 TypeError: Cannot destructure property 'label' of 'd.find(...)' as it is undefined.
    at c (ResourceSortDropdown.tsx:38:10)
    at ca (react-dom.production.min.js:157:137)
    at Vc (react-dom.production.min.js:267:460)
    at Ts (react-dom.production.min.js:250:347)
    at Es (react-dom.production.min.js:250:278)
    at Ss (react-dom.production.min.js:250:138)
    at vs (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Go (react-dom.production.min.js:122:325)

errors.ts:63 
 TypeError: Cannot destructure property 'label' of 'd.find(...)' as it is undefined.
    at c (ResourceSortDropdown.tsx:38:10)
    at ca (react-dom.production.min.js:157:137)
    at Vc (react-dom.production.min.js:267:460)
    at Ts (react-dom.production.min.js:250:347)
    at Es (react-dom.production.min.js:250:278)
    at Ss (react-dom.production.min.js:250:138)
    at vs (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Go (react-dom.production.min.js:122:325)
```
