### ISSUE TITLE
Cannot read properties of null (reading '0') in Data Explorer when trying to see graph results

### ISSUE THREAD

**Issue by twillhorn** [influxdata/ui#6862]
In the Data Explorer, after running a query and seeing tabular results, when I click "GRAPH" I get an error and have to refresh. This is reproducible. The last time the graph worked I was exploring different graph settings. I'm thinking some bad setting is saved now and I can't change/reset them anymore.

Even a simple query like "SELECT time, val FROM measurement" crashes when attempting to graph.

```
react-dom.production.min.js:216 TypeError: Cannot read properties of null (reading '0')
    at ys (index.ts:30:36)
    at j (view.tsx:248:29)
    at sa (react-dom.production.min.js:157:137)
    at qs (react-dom.production.min.js:267:460)
    at Ml (react-dom.production.min.js:250:347)
    at Tl (react-dom.production.min.js:250:278)
    at Dl (react-dom.production.min.js:250:138)
    at Al (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
us @ react-dom.production.min.js:216
n.payload @ react-dom.production.min.js:217
hi @ react-dom.production.min.js:130
Va @ react-dom.production.min.js:182
qs @ react-dom.production.min.js:269
Ml @ react-dom.production.min.js:250
Tl @ react-dom.production.min.js:250
Dl @ react-dom.production.min.js:250
Al @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wo @ react-dom.production.min.js:122
Ko @ react-dom.production.min.js:123
Zo @ react-dom.production.min.js:122
Pe @ react-dom.production.min.js:292
Kt @ react-dom.production.min.js:73
N.e.___hb.e.___hb @ honeybadger.js:495
```

**Comment by twillhorn** [comment]
I worked around this by creating a new script

**Comment by zoesteinkamp** [comment]
Im glad it worked out :)

Im going to close this issue for now, but please reopen it if you feel you need further help
