### ISSUE TITLE
Request TImeout

### ISSUE THREAD

**Issue by rahulAccelalpha** [influxdata/ui#6876]
i am using Nodejs Influx library and while inserting any record it is throwing request timeout error

```
WARN: Write to InfluxDB failed (attempt: 1). x [RequestTimedOutError]: Request timed out
    at ClientRequest.<anonymous> (E:\timestreamdb\node_modules\@influxdata\influxdb-client\dist\index.js:5:6447)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.emitRequestTimeout (node:_http_client:847:9)
    at Object.onceWrapper (node:events:628:28)
    at TLSSocket.emit (node:events:526:35)
    at Socket._onTimeout (node:net:571:8)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
ERROR: Retry buffer closed with 1 items that were not written to InfluxDB! 
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

x [RequestTimedOutError]: Request timed out
    at ClientRequest.<anonymous> (E:\timestreamdb\node_modules\@influxdata\influxdb-client\dist\index.js:5:6447)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.emitRequestTimeout (node:_http_client:847:9)
    at Object.onceWrapper (node:events:628:28)
    at TLSSocket.emit (node:events:526:35)
    at Socket._onTimeout (node:net:571:8)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

**Comment by zoesteinkamp** [comment]
Which nodejs client library? can you link it? And then i think this error might need to be on the client library not on the ui
